homepage:
    path:     /
    defaults: { _controller: JamesMannionForumBundle:Building:index }

JamesMannionForumBundle_building:
    resource: "@JamesMannionForumBundle/Resources/config/routing/building.yml"
    prefix:   /buildings

JamesMannionForumBundle_room:
    resource: "@JamesMannionForumBundle/Resources/config/routing/room.yml"
    prefix:   /rooms

JamesMannionForumBundle_thread:
    resource: "@JamesMannionForumBundle/Resources/config/routing/thread.yml"
    prefix:   /threads

JamesMannionForumBundle_post:
    resource: "@JamesMannionForumBundle/Resources/config/routing/post.yml"
    prefix:   /posts