homepage:
    path:     /
    defaults: { _controller: JamesMannionForumBundle:Content:index }

JamesMannionForumBundle_enquiry:
    resource: "@JamesMannionForumBundle/Resources/config/routing/enquiry.yml"
    prefix:   /enquiry

JamesMannionForumBundle_room:
    resource: "@JamesMannionForumBundle/Resources/config/routing/room.yml"
    prefix:   /room

JamesMannionForumBundle_thread:
    resource: "@JamesMannionForumBundle/Resources/config/routing/thread.yml"
    prefix:   /thread

JamesMannionForumBundle_post:
    resource: "@JamesMannionForumBundle/Resources/config/routing/post.yml"
    prefix:   /post