homepage:
    path:     /
    defaults: { _controller: JamesMannionForumBundle:Content:index }

JamesMannionForumBundle_enquiries:
    resource: "@JamesMannionForumBundle/Resources/config/routing/enquiry.yml"
    prefix:   /enquiries

JamesMannionForumBundle_room:
    resource: "@JamesMannionForumBundle/Resources/config/routing/room.yml"
    prefix:   /rooms

JamesMannionForumBundle_thread:
    resource: "@JamesMannionForumBundle/Resources/config/routing/thread.yml"
    prefix:   /threads

JamesMannionForumBundle_post:
    resource: "@JamesMannionForumBundle/Resources/config/routing/post.yml"
    prefix:   /posts