JamesMannionForumBundle_homepage:
    path:     /
    defaults: { _controller: JamesMannionForumBundle:Building:index }

JamesMannionForumBundle_building:
    resource: "@JamesMannionForumBundle/Resources/config/routing/building.yml"
    prefix:   /buildings

JamesMannionForumBundle_room:
    resource: "@JamesMannionForumBundle/Resources/config/routing/room.yml"
    prefix:   /rooms

JamesMannionForumBundle_thread:
    resource: "@JamesMannionForumBundle/Resources/config/routing/thread.yml"
    prefix:   /threads

JamesMannionForumBundle_post:
    resource: "@JamesMannionForumBundle/Resources/config/routing/post.yml"
    prefix:   /posts

JamesMannionForumBundle_user:
    resource: "@JamesMannionForumBundle/Resources/config/routing/user.yml"
    prefix:   /user


### USER ROUTES ###

### AUTHENTICATION CHECK ###

JamesMannionForumBundle_login:
    pattern: /login
    defaults: { _controller: JamesMannionForumBundle:Authentication:login }
    requirements:
        _method: GET

JamesMannionForumBundle_check:
    pattern: /system/login_check
    requirements:
        _method: POST

JamesMannionForumBundle_logout:
    pattern: /system/logout
    requirements:
        _method: GET