parameters:
    webservice_user_provider.class: JamesMannion\ForumBundle\Security\User\ForumUser

services:
    authentication_handler:
        class: JamesMannion\ForumBundle\Handler\AuthenticationHandler
        calls:
            - [ setContainer, [ @service_container ] ]

    post_listener:
        class: JamesMannion\ForumBundle\EventListener\PostListener
        arguments:
            mailer: "@mailer"
        tags:
            - { name: kernel.event_listener, event: postCreated, method: onPostCreatedEvent }

    user_listener:
        class: JamesMannion\ForumBundle\EventListener\UserListener
        arguments:
            mailer: "@mailer"
        tags:
            - { name: kernel.event_listener, event: userRegistered, method: onUserRegisteredEvent }

    post_manager:
        class: JamesMannion\ForumBundle\Entity\PostManager
        arguments:
            em: "@doctrine.orm.entity_manager"
            class: FooVendorBarBundleEntityComment

    base_manager:
        abstract: true
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]

    post_manager:
        class: JamesMannion\ForumBundle\Manager\PostManager
        arguments: ["JamesMannionForumBundle\Entity\Post"]
        parent: base_manager