parameters:
#    james_mannion_forum.example.class: JamesMannion\ForumBundle\Example

services:
    acme_user.registration.form.type:
        class: JamesMannion\ForumBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: forum_user_registration }