post:
    path:     /post/
    defaults: { _controller: "JamesMannionForumBundle:Post:index" }

post_show:
    path:     /post/{id}/show
    defaults: { _controller: "JamesMannionForumBundle:Post:show" }

post_new:
    path:     /secure/post/new/{id}
    defaults: { _controller: "JamesMannionForumBundle:Post:new" }
    requirements:
        roomId: \d+

post_create:
    path:     /secure/post/create/{id}
    defaults: { _controller: "JamesMannionForumBundle:Post:create" }
    requirements: { _method: post }

post_edit:
    path:     /secure/post/edit/{id}
    defaults: { _controller: "JamesMannionForumBundle:Post:edit" }

post_update:
    path:     /secure/post/{id}/update
    defaults: { _controller: "JamesMannionForumBundle:Post:update" }
    requirements: { _method: post|put }

post_delete:
    path:     /secure/post/{id}/delete
    defaults: { _controller: "JamesMannionForumBundle:Post:delete" }
    requirements: { _method: post|delete }

post_like_toggle:
    path:     /secure/post/{id}/like
    defaults: { _controller: "JamesMannionForumBundle:Post:likeToggle" }
    requirements: { _method: get }