post:
    path:     /
    defaults: { _controller: "JamesMannionForumBundle:Post:index" }

post_show:
    path:     /{id}/show
    defaults: { _controller: "JamesMannionForumBundle:Post:show" }

post_new:
    path:     /new/{id}
    defaults: { _controller: "JamesMannionForumBundle:Post:new" }
    requirements:
        roomId: \d+

post_create:
    path:     /create/{id}
    defaults: { _controller: "JamesMannionForumBundle:Post:create" }
    requirements: { _method: post }

post_edit:
    path:     /{id}/edit
    defaults: { _controller: "JamesMannionForumBundle:Post:edit" }

post_update:
    path:     /{id}/update
    defaults: { _controller: "JamesMannionForumBundle:Post:update" }
    requirements: { _method: post|put }

post_delete:
    path:     /{id}/delete
    defaults: { _controller: "JamesMannionForumBundle:Post:delete" }
    requirements: { _method: post|delete }
