thread:
    path:     /thread/
    defaults: { _controller: "JamesMannionForumBundle:Thread:index" }

thread_show:
    path:     /thread/{id}/show
    defaults: { _controller: "JamesMannionForumBundle:Thread:show" }

thread_new:
    path:     /secure/thread/new/{id}
    defaults: { _controller: "JamesMannionForumBundle:Thread:new"}
    requirements:
        roomId: \d+

thread_create:
    path:     /secure/thread/create/{id}
    defaults: { _controller: "JamesMannionForumBundle:Thread:create" }
    requirements: { _method: post }

thread_edit:
    path:     /secure/thread/{id}/edit
    defaults: { _controller: "JamesMannionForumBundle:Thread:edit" }

thread_update:
    path:     /secure/thread/{id}/update
    defaults: { _controller: "JamesMannionForumBundle:Thread:update" }
    requirements: { _method: post|put }

thread_delete:
    path:     /secure/thread/{id}/delete
    defaults: { _controller: "JamesMannionForumBundle:Thread:delete" }
    requirements: { _method: post|delete }
