thread:
    path:     /
    defaults: { _controller: "JamesMannionForumBundle:Thread:index" }

thread_show:
    path:     /{id}/show
    defaults: { _controller: "JamesMannionForumBundle:Thread:show" }

thread_new:
    path:     /new/{roomId}
    defaults: { _controller: "JamesMannionForumBundle:Thread:new"}
    requirements:
        roomId: \d+

thread_create:
    path:     /create
    defaults: { _controller: "JamesMannionForumBundle:Thread:create" }
    requirements: { _method: post }

thread_edit:
    path:     /{id}/edit
    defaults: { _controller: "JamesMannionForumBundle:Thread:edit" }

thread_update:
    path:     /{id}/update
    defaults: { _controller: "JamesMannionForumBundle:Thread:update" }
    requirements: { _method: post|put }

thread_delete:
    path:     /{id}/delete
    defaults: { _controller: "JamesMannionForumBundle:Thread:delete" }
    requirements: { _method: post|delete }
