user:
    path:     /
    defaults: { _controller: "JamesMannionForumBundle:User:index" }
    requirements:
        _method: GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "JamesMannionForumBundle:User:show" }
    requirements:
        _method: GET

JamesMannionForumBundle_userCreate:
    pattern:  /register
    defaults: { _controller: JamesMannionForumBundle:User:create }
    requirements:
        _method: GET

JamesMannionForumBundle_userCreated:
    pattern:  /register-success
    defaults: { _controller: JamesMannionForumBundle:User:create }
    requirements:
        _method: POST

userEdit:
    path:     /profile
    defaults: { _controller: "JamesMannionForumBundle:User:edit" }
    requirements:
        _method: GET

userUpdate:
    path:     /profile/update
    defaults: { _controller: "JamesMannionForumBundle:User:update" }
    requirements: { _method: post|put }