security:
    encoders:
        JamesMannion\ForumBundle\Entity\User:
            algorithm: bcrypt
            cost: 7
        JamesMannion\ForumBundle\Entity\Admin:
            algorithm: bcrypt
            cost: 7

    providers:
        users:
            entity: { class: JamesMannionForumBundle:User, property: username }
        admins:
            entity: { class: JamesMannionForumBundle:Admin, property: username }

    role_hierarchy:
        ROLE_USER:        ROLE_USER
        ROLE_ADMIN:       [ROLE_USER, ROLE_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_SUPER_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        system:
            pattern:    ^/
            form_login:
                success_handler: authentication_handler
                check_path: JamesMannionForumBundle_check
                login_path: JamesMannionForumBundle_login
                default_target_path: JamesMannionForumBundle_dashboardShow
            logout:
                path:   JamesMannionForumBundle_logout
                target: JamesMannionForumBundle_homepage
            anonymous: ~

    access_control:
        - { path: ^/threads/new/, roles: ROLE_USER }
        - { path: ^/system, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }